/**
 * Angular JS Module
 */
var app= angular.module("app",['ngRoute','ngCookies']);
app.config(function($routeProvider){
	$routeProvider
		.when('/register',{
			templateUrl:'views/registrationform.html',
			controller:'UserController'
		})
		.when('/home',{
			templateUrl:'views/home.html'
		})
		.when('/login',{
			templateUrl:'views/login.html',
			controller:'UserController'
		})
		.when('/editProfile',{
			templateUrl:'views/editProfile.html',
			controller:'UserController'
		})
		.when('/createBlog',{
			templateUrl:'views/createBlog.html',
			controller:'BlogController'
		})
		.when('/getAllBlogs',{
			templateUrl:'views/getBlogs.html',
			controller:'BlogController'
		})
		.when('/getBlogByID/:id',{
			templateUrl:'views/blogdetails.html',
			controller:'BlogDetailController'
		})
		.when('/getApprovalForm/:id',{
			templateUrl:'views/approvalBlogForm.html',
			controller:'BlogDetailController'
		})
		.otherwise({
			templateUrl:'views/home.html'
		})
})
app.run(function($rootScope,$cookieStore,UserService,$location){
	if($rootScope.currentUser==undefined)
	{	
			$rootScope.currentUser=$cookieStore.get('userDetails')
			console.log($cookieStore.get('userDetails'));
	}	
})