/**
 * Angular JS Module
 */
var app= angular.module("app",['ngRoute','ngCookies']);
app.config(function($routeProvider){
	$routeProvider
		.when('/register',{
			templateUrl:'views/registrationform.html',
			controller:'UserController'
		})
		.when('/home',{
			templateUrl:'views/home.html'
		})
		.when('/login',{
			templateUrl:'views/login.html',
			controller:'UserController'
		})
		.when('/editProfile',{
			templateUrl:'views/editProfile.html',
			controller:'UserController'
		})
		.when('/createBlog',{
			templateUrl:'views/createBlog.html',
			controller:'BlogController'
		})
		.when('/getAllBlogs',{
			templateUrl:'views/getBlogs.html',
			controller:'BlogController'
		})
		.when('/getBlogByID/:id',{
			templateUrl:'views/blogdetails.html',
			controller:'BlogDetailController'
		})
		.when('/getApprovalForm/:id',{
			templateUrl:'views/approvalBlogForm.html',
			controller:'BlogDetailController'
		})
		.when('/addJob',{
			templateUrl:'views/addJob.html',
			controller : 'JobController'
		})
		.when('/getAllJobs',{
			templateUrl:'views/getAllJobs.html',
			controller:'JobController'
		})
		.when('/uploadProfilePic',{
			templateUrl:'views/uploadProfilePic.html',
			
		})
		.otherwise({
			templateUrl:'views/home.html'
		})
})
